[package]
name = "traceon"
version = "0.1.2"
authors = ["Jack Clayton <jackos@me.com>"]
edition = "2021"
license = "MIT/Apache-2.0"
repository = "https://github.com/jackos/traceon"
documentation = "https://docs.rs/traceon"
readme = "README.md"
description = "Trace on json, easy to use tracing formatter"
keywords = ["logging", "metrics", "tracing", "subscriber"]
categories = ["development-tools::profiling", "development-tools::debugging"]

[dependencies]
tracing = { version = "0.1", default-features = false, features = [
	"log",
	"std",
] }
tracing-subscriber = { version = "0.3", default-features = false, features = [
	"registry",
	"fmt",
	"env-filter",
] }
tracing-log = { version = "0.1" }
log = "0.4"
serde_json = { version = "1" }
serde = "1"
tracing-core = "0.1"
time = { version = "0.3", default-features = false, features = ["formatting"] }

[dev-dependencies]
claims = "0.6.0"
lazy_static = "1.4.0"
tracing-subscriber = { version = "0.3", default-features = false, features = [
	"registry",
	"fmt",
	"env-filter",
	"json",
] }
tracing = { version = "0.1.13", default-features = false, features = [
	"log",
	"std",
	"attributes",
] }
time = { version = "0.3", default-features = false, features = [
	"formatting",
	"parsing",
	"local-offset",
] }
tokio = { version = "1.23.0", features = ["full"] }
criterion = { version = "0.4.0", features = ["html_reports", "async_tokio"] }

[[bench]]
name = "tracing"
harness = false
