[package]
name = "traceon"
version = "0.2.0"
authors = ["Jack Clayton <jackos@me.com>"]
edition = "2021"
license = "MIT/Apache-2.0"
repository = "https://github.com/jackos/traceon"
documentation = "https://docs.rs/traceon"
readme = "README.md"
description = "Trace on json, easy to use tracing formatter"
keywords = ["logging", "metrics", "tracing", "subscriber"]
categories = ["development-tools::profiling", "development-tools::debugging"]

[dependencies]
log = "0.4"
tracing-core = "0.1"
tracing-log = "0.1"
serde = "1"
serde_json = "1"
time = { version = "0.3", default-features = false, features = [
	"formatting",
	"macros",
] }
nu-ansi-term = "0.46.0"
chrono = "0.4.23"

[dependencies.tracing-subscriber]
version = "0.3"
default-features = false
features = ["registry", "fmt", "env-filter"]

[dependencies.tracing]
version = "0.1"
default-features = false
features = ["log", "std"]

[dev-dependencies]
claims = "0.6.0"
lazy_static = "1.4.0"
tokio = { version = "1.23.0", features = ["full"] }
criterion = { version = "0.4.0", features = ["html_reports", "async_tokio"] }
tracing-appender = "0.2.2"

[dev-dependencies.tracing-subscriber]
version = "0.3"
# default-features = false
features = ["registry", "fmt", "env-filter", "json"]

[dev-dependencies.tracing]
version = "0.1"
default-features = false
features = ["log", "std", "attributes"]

[dev-dependencies.time]
version = "0.3"
default-features = false
features = ["formatting", "parsing", "local-offset"]

[[bench]]
name = "tracing"
harness = false

[[bench]]
name = "async"
harness = false
